# Generated by Django 4.1 on 2023-04-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="blogs", to="main.tag"
            ),
        ),
    ]
